SIMPLY-4066: Add DS Components
NYPL-Simplified/registry_admin pull request #80
Opened 2022-06-07 19:04 UTC by oliviawongnyc

**Description**

- Adds Reservoir (Design System) components to the new Registry Admin Parcel app.
- Adds snapshot and unit tests for the top-level AdminPage, as well as the LibraryDetails component.

**Notes**

- Uses createRoot instead of ReactDOM.render (https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis), though I still get an error while testing.
- Reservoir CSS file cannot be imported. Edwin is working on this. See [DSD-1001.](https://jira.nypl.org/browse/DSD-1001)

2022-06-08 15:18 UTC, samanthaandrews requested changes
Just a few small things & a couple questions. Whenever the CSS stuff is added go ahead and re-request review!

2022-06-09 14:52 UTC, oliviawongnyc commented on package.json
> +    "process": "^0.11.10",
Yeah, I am curious about this too. I didn't install in manually. I even uninstalled it, and it returned.... Should I be worried? Tried uninstalling again, we'll see what happens.

2022-06-15 18:19 UTC, oliviawongnyc commented on src/components/LibraryDetails.tsx
> +  const [registryStage, setRegistryStage] = useState<string>('');
Done!

2022-06-28 14:34 UTC, samanthaandrews commented on package.json
> +    "process": "^0.11.10",
Got it, thanks for checking!

2022-06-28 14:35 UTC, samanthaandrews approved these changes

2022-06-29 14:07 UTC, merged